use UNIVER;

select GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where GROUPS.FACULTY = '’“Ë“'
GROUP BY ROLLUP (GROUPS.PROFESSION, PROGRESS.SUBJECT)

select GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where GROUPS.FACULTY = '’“Ë“'
GROUP BY CUBE (GROUPS.PROFESSION, PROGRESS.SUBJECT)

select GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from GROUPS, PROGRESS, STUDENT
where GROUPS.FACULTY = '’“Ë“'
GROUP BY GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
UNION
select GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from GROUPS, PROGRESS, STUDENT
where GROUPS.FACULTY = '“Œ¬'
GROUP BY GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT

select GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from GROUPS, PROGRESS, STUDENT
where GROUPS.FACULTY = '’“Ë“'
GROUP BY GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
UNION ALL
select GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from GROUPS, PROGRESS, STUDENT
where GROUPS.FACULTY = '“Œ¬'
GROUP BY GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT

select GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from GROUPS, PROGRESS, STUDENT
where GROUPS.FACULTY = '’“Ë“'
GROUP BY GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
EXCEPT
select GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(NOTE as float)),2)NOTE
from GROUPS, PROGRESS, STUDENT
where GROUPS.FACULTY = '“Œ¬'
GROUP BY GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT